//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivityLogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
        public int id { get; set; }
        public int account_id { get; set; }
        public Nullable<decimal> duration { get; set; }
        public string activity_name { get; set; }
        public Nullable<System.DateTime> date_started { get; set; }
        public Nullable<System.DateTime> date_ended { get; set; }
    
        public virtual account account { get; set; }
    }
}
